package com.smartfitagent.db;
import com.smartfitagent.model.*; import java.sql.*; import java.time.*; import java.util.*;
public class MySqlDatabase implements Database {
 private final String url=System.getenv().getOrDefault("MYSQL_URL","jdbc:mysql://127.0.0.1:3306/smart_study_agent?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai"); private final String user=System.getenv().getOrDefault("MYSQL_USER","root"); private final String password=System.getenv().getOrDefault("MYSQL_PASSWORD","root");
 public MySqlDatabase(){ try{Class.forName("com.mysql.cj.jdbc.Driver");}catch(Exception e){throw new IllegalStateException("缺少mysql-connector-j.jar");} }
 public void init() throws Exception { try(Connection c=conn(); Statement s=c.createStatement()){ s.executeUpdate("CREATE TABLE IF NOT EXISTS users(id VARCHAR(64) PRIMARY KEY,name VARCHAR(100),grade VARCHAR(100),goal TEXT,weakness TEXT,preferred_style VARCHAR(200))"); s.executeUpdate("CREATE TABLE IF NOT EXISTS courses(id VARCHAR(64) PRIMARY KEY,title VARCHAR(200),subject VARCHAR(100),level VARCHAR(100),description TEXT,lessons INT,teacher VARCHAR(100),progress INT)"); s.executeUpdate("CREATE TABLE IF NOT EXISTS plans(id VARCHAR(64) PRIMARY KEY,title VARCHAR(200),subject VARCHAR(100),plan_date DATE,minutes INT,steps TEXT,status VARCHAR(100))"); s.executeUpdate("CREATE TABLE IF NOT EXISTS notes(id VARCHAR(64) PRIMARY KEY,title VARCHAR(200),subject VARCHAR(100),content TEXT,tags VARCHAR(200),created_at VARCHAR(64))"); s.executeUpdate("CREATE TABLE IF NOT EXISTS questions(id VARCHAR(64) PRIMARY KEY,subject VARCHAR(100),stem TEXT,option_a TEXT,option_b TEXT,option_c TEXT,option_d TEXT,answer VARCHAR(20),explanation TEXT)"); s.executeUpdate("CREATE TABLE IF NOT EXISTS attempts(id VARCHAR(64) PRIMARY KEY,subject VARCHAR(100),score INT,total INT,mistakes TEXT,created_at VARCHAR(64))"); } }
 public String name(){return "mysql:"+url;} private Connection conn() throws Exception{return DriverManager.getConnection(url,user,password);} private void up(String sql,Object...a){try(Connection c=conn(); PreparedStatement p=c.prepareStatement(sql)){for(int i=0;i<a.length;i++)p.setObject(i+1,a[i]);p.executeUpdate();}catch(Exception e){throw new IllegalStateException(e);}}
 public Optional<UserProfile> user(){try(Connection c=conn(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT * FROM users LIMIT 1")){if(r.next())return Optional.of(new UserProfile(r.getString("id"),r.getString("name"),r.getString("grade"),r.getString("goal"),r.getString("weakness"),r.getString("preferred_style"),0.0,0.0));return Optional.empty();}catch(Exception e){throw new IllegalStateException(e);}}
 public void saveUser(UserProfile u){up("REPLACE INTO users VALUES(?,?,?,?,?,?)",u.id(),u.name(),u.grade(),u.goal(),u.weakness(),u.preferredStyle());}
 public List<Course> courses(){List<Course> list=new ArrayList<>(); try(Connection c=conn(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT * FROM courses")){while(r.next())list.add(new Course(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getInt(6),r.getString(7),r.getInt(8)));}catch(Exception e){throw new IllegalStateException(e);} return list;} public void saveCourse(Course x){up("REPLACE INTO courses VALUES(?,?,?,?,?,?,?,?)",x.id(),x.title(),x.subject(),x.level(),x.description(),x.lessons(),x.teacher(),x.progress());}
 public List<StudyPlan> plans(){List<StudyPlan> list=new ArrayList<>(); try(Connection c=conn(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT * FROM plans")){while(r.next())list.add(new StudyPlan(r.getString(1),r.getString(2),r.getString(3),LocalDate.parse(r.getString(4)),r.getInt(5),r.getString(6),r.getString(7)));}catch(Exception e){throw new IllegalStateException(e);} return list;} public void savePlan(StudyPlan x){up("REPLACE INTO plans VALUES(?,?,?,?,?,?,?)",x.id(),x.title(),x.subject(),x.date().toString(),x.minutes(),x.steps(),x.status());}
 public List<Note> notes(){List<Note> list=new ArrayList<>(); try(Connection c=conn(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT * FROM notes")){while(r.next())list.add(new Note(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),LocalDateTime.parse(r.getString(6))));}catch(Exception e){throw new IllegalStateException(e);} return list;} public void saveNote(Note x){up("REPLACE INTO notes VALUES(?,?,?,?,?,?)",x.id(),x.title(),x.subject(),x.content(),x.tags(),x.createdAt().toString());}
 public List<QuizQuestion> questions(){List<QuizQuestion> list=new ArrayList<>(); try(Connection c=conn(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT * FROM questions")){while(r.next())list.add(new QuizQuestion(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9)));}catch(Exception e){throw new IllegalStateException(e);} return list;} public void saveQuestion(QuizQuestion x){up("REPLACE INTO questions VALUES(?,?,?,?,?,?,?,?,?)",x.id(),x.subject(),x.stem(),x.optionA(),x.optionB(),x.optionC(),x.optionD(),x.answer(),x.explanation());}
 public List<QuizAttempt> attempts(){List<QuizAttempt> list=new ArrayList<>(); try(Connection c=conn(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT * FROM attempts")){while(r.next())list.add(new QuizAttempt(r.getString(1),r.getString(2),r.getInt(3),r.getInt(4),r.getString(5),LocalDateTime.parse(r.getString(6))));}catch(Exception e){throw new IllegalStateException(e);} return list;} public void saveAttempt(QuizAttempt x){up("REPLACE INTO attempts VALUES(?,?,?,?,?,?)",x.id(),x.subject(),x.score(),x.total(),x.mistakes(),x.createdAt().toString());}
}
